# Generated by Django 3.1.2 on 2020-10-20 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201015_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.category'),
        ),
    ]
