# Generated by Django 3.1.2 on 2020-10-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_category_sub_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sub_menu',
            new_name='child_of',
        ),
        migrations.AddField(
            model_name='category',
            name='is_child_menu',
            field=models.BooleanField(default=False),
        ),
    ]
