# Generated by Django 3.1.2 on 2020-10-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20201020_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='child_of',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_child_menu',
        ),
        migrations.AddField(
            model_name='category',
            name='child_menus',
            field=models.ManyToManyField(blank=True, null=True, related_name='_category_child_menus_+', to='post.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_parent_menu',
            field=models.BooleanField(default=True),
        ),
    ]
