# Generated by Django 3.1.2 on 2020-10-22 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20201020_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_category', to='post.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='child_menus',
            field=models.ManyToManyField(blank=True, related_name='_category_child_menus_+', to='post.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='post.category'),
        ),
    ]
